language: r
warnings_are_errors: true
cache: packages
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
dist: trusty
addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libxml2-dev
    - libfftw3-dev
    - libgsl0-dev
    - mesa-common-dev
    - libglu1-mesa-dev
    - devscripts
    - jags
os:
- linux
- osx
osx_image: xcode9.4
services: xvfb
r:
- 3.3
- 3.4
- 3.5
- release
- devel
matrix:
  allow_failures:
  - r: devel
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=oslerinhealth
  - DISPLAY=:99.0
  - R_REMOTES_NO_ERRORS_FROM_WARNINGS=true
  - _R_CHECK_FORCE_SUGGESTS_=false
  - CACHE_NAME="${TRAVIS_OS_NAME}-R-${TRAVIS_R_VERSION}"
r_check_args: "--as-cran --install-args=--build"
before_install:
- if [ "$TRAVIS_DIST" = "trusty" ]; then sudo apt-get -y install libgsl0ldbl ; fi
- ulimit -n 2048
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- codename=`linux_codename`;
- start_xvfb ;
- export rver=`r_version`; echo $rver ;
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; brew install -v freetype ; fi
- jags_install || true;
- if `need_v8`; then v8_install || true; fi
- dcmtk_install || true;
- gsl_install 2.1 || true ;
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- echo "Package Name is $PACKAGE_NAME"
- setup_python 3.6 false ;
- install_python_requirements ;
after_success: dump_logs
after_failure: dump_logs
before_deploy:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then PKG_TARBALL=$(ls -1t *.tgz | head -n 1);
  PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tgz/_'"R${rver}"'.tgz/'` ; mv ${PKG_TARBALL}
  ${PKG_TARBALL_WITH_R} ; echo "Built tarball is ${PKG_TARBALL_WITH_R}" ; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then PKG_TARBALL=$(ls -1t *.tar.gz | head -n
  1); PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tar.gz/_'"R${rver}"'.tar.gz/'`
  ; mv ${PKG_TARBALL} ${PKG_TARBALL_WITH_R} ; echo "Built tarball is ${PKG_TARBALL_WITH_R}"
  ; fi
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  overwrite: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: YlLniB1xp/j7jQBSyEfQivK43FrszvV4yGg/S5ea0R00IJ6fhTAYk+0tukZrTgWuYG440VSFuNnAL+QUKRTx9x6JJIUsfz3G9mm0heweEUgIHi/2M+M61Q5UcqIwlGDT21uezIxx+K/QpEOnT58oMgq/9ErpXtyi9n+hHNWry+tcRfrdXbKTP0i9IWoppGm4UQ4d2/hCK/96GQYVkuRMTIdvJiqUipkIjZxR8nVddjWjfj8TOMiQogMm4PK3cNRRI/cpB5vYJxuBu8SfA7bfIiwlk02rJwbnx6l91qCweYUdViI4mf0PHNV/7P0laXnemU40u2jWoacd+Mz5hUQLWtQQyS2i0YZqsh+b9ucyn2SedLmrWHNo3loLrzvL+E6q/6mngTxgHmHhb6ETf0ZugcQfCkNy3KEWwKFKbebr7ZoAtuSy27iKw4UQw7pznHgHYpbhWAP2FjwjSki7HgZcdCWd4L35jLTz4IIO6jkO5D7Th0YpYaWbBmkq0s+HgSDRtweAnDPzbtVs9DGLV2IxeRusVjDYR1fMVC3pivqQx9YEPER0Fxa17OFLou/N9D44zFKTm2WlSWFp9aVCEmiu02l18yniHt0X6Gy/dejbo4Wx8Xd3E1zEQd1wMUfleYdh7YzTJ/ITtvBH7c13NpPk2GLMX7r20y6m6TWlLMFOmDk=
after_deploy:
- echo "${PROJECT_NAME}" | grep -q "releases"; if [[ $? -eq 0 ]]; then run_coverage="false";
  else run_coverage=; fi;
- if [[ "${TRAVIS_OS_NAME}" == "linux" && ${TRAVIS_R_VERSION_STRING} = "release" &&
  -z "${run_coverage}" ]]; then echo 'covr::coveralls(type = "all", quiet = FALSE)'
  > osler_covr.R ; travis_wait 100 Rscript osler_covr.R ; rm osler_covr.R ; fi

#neuroc.deps version (SHA): 3b42e5b